version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ${PWD}/docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/api/:/srv/www:cached
    ports:
      - "80:80"
    depends_on:
      - php
    links:
      - php
      - mysql

  php:
    container_name: php
    build:
      context: ${PWD}/docker/php
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/api/:/srv/www:cached
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: database
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: symfony-api-db
      MYSQL_USER: samuel
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql